### ISSUE TITLE
Closing VRC after using tool makes SteamVR think VRC is still open

### ISSUE THREAD

**Issue by ArchOwlen** [LudoDash/NoEac#1]
When closing VRC (tried various methods including task manager killing VRC) steam still detects VRC as open even though it is not

Killing various things in task manager doesn't help, only is fixed after a reboot

**Comment by L-udo** [comment]
> When closing VRC (tried various methods including task manager killing VRC) steam still detects VRC as open even though it is not
> 
> Killing various things in task manager doesn't help, only is fixed after a reboot

Not an issue with Vrchat minus.
This is a problem with VRChat itself & steam.
Sadly the only way to avoid it is opening and closing vrchat via steam.

We will probably implement a 3rd part fix for it.
But the best place to report the bug, would be to steam.
